name: Push to Docker Hub

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3      
      - name: dockerhub login
        run: echo ${{ secrets.DOCKER_PASSWORD }} docker login -u ${{ secrets.DOCKER_USER }} 
      - name: docker buildx
        run: |
          docker buildx build . \
          --build-arg BW_CLI_VERSION=${{ github.event.inputs.version }} \ 
          --file Dockerfile \ 
          --platform linux/amd64,linux/arm64 \
          --tag ${{ secrets.DOCKER_USER }}/bw-cli:latest \
          --tag ${{ secrets.DOCKER_USER }}/bw-cli:${{ github.event.inputs.version }} \
          --push
